### ISSUE TITLE
Enable SDK unique name

### ISSUE THREAD

**Issue by xuhao1** [lanyusea/djiros#18]
I will add a parameter to enable unique id on topic name.

**Comment by lanyusea** [comment]
already therer

**Comment by lanyusea** [comment]
please refer to the 2.3 branch's launch file with name "swarm"

**Comment by lanyusea** [comment]
Also, DO NOT push to the 3.1 branch directly.

Check out a new branch for your toy, this one should be kept clean and clear before pushing into the official repo.

The dji ros is more specified as a sdk testing role for navigation and flight control department, instead of fancy(or creepy) function enhancement.
